baseURL = ""
languageCode = "en-us"
title = "Jack B. Muir"
theme = "jbmuir-theme"
contentdir = "content" 
layoutdir = "layouts" 
publishdir = "public" 
MetaDataFormat = "toml" 
[indexes] 
    category = "categories" 
    tag = "tags" 
[author] 
    name = "Jack B. Muir" 